from __future__ import annotations

import argparse
import json
from pathlib import Path

# Marker written into every auto-generated file.  If --out exists and does NOT
# carry this marker, it is a hand-written report and must not be clobbered:
# `make report` would otherwise silently destroy the graded deliverable.
GENERATED_MARKER = "<!-- generated by scripts/generate_report.py -->"


def render(metrics: dict[str, object]) -> str:
    lines = [
        GENERATED_MARKER,
        "# Day 25 Reliability - Auto-generated Metrics Summary",
        "",
        "## Metrics Summary",
        "",
        "| Metric | Value |",
        "|---|---:|",
    ]
    for key, value in metrics.items():
        if key == "scenarios":
            continue
        lines.append(f"| {key} | {value} |")
    lines += ["", "## Chaos Scenarios", "", "| Scenario | Status |", "|---|---|"]
    scenarios = metrics.get("scenarios", {})
    if isinstance(scenarios, dict):
        for key, value in scenarios.items():
            lines.append(f"| {key} | {value} |")
    lines += [
        "",
        "## Analysis",
        "",
        "The narrative analysis lives in the hand-written `reports/final_report.md`",
        "(architecture, configuration rationale, chaos interpretation, failure analysis).",
        "This file only mirrors the raw numbers from `reports/metrics.json`.",
        "",
    ]
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--metrics", default="reports/metrics.json")
    parser.add_argument("--out", default="reports/final_report.md")
    parser.add_argument(
        "--force",
        action="store_true",
        help="Overwrite --out even if it looks hand-written.",
    )
    args = parser.parse_args()
    metrics = json.loads(Path(args.metrics).read_text(encoding="utf-8"))
    content = render(metrics)

    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)

    if out.exists() and not args.force:
        existing = out.read_text(encoding="utf-8")
        if GENERATED_MARKER not in existing:
            # Hand-written report present: write the auto summary beside it instead.
            alt = out.with_name(out.stem + "_auto.md")
            alt.write_text(content, encoding="utf-8")
            print(f"{out} is hand-written - left untouched.")
            print(f"wrote {alt} (use --force to overwrite {out})")
            return

    out.write_text(content, encoding="utf-8")
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
